version: '3.4'

services:
  web:
    image: web
    build:
      context: Web
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  api:
    image: api
    depends_on:
      - reverseproxy 
    build:
      context: Api
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development #TODO: CHANGE THIS 
    ports:
      - 7167:7167

