version: '3.4'

services:
  reverseproxy:
    image: reverseproxy
    build:
      context: Nginx
      dockerfile: ./Dockerfile
    ports:
      - "443:443" 
      - "80:80" 
    restart: always
  web:
    image: web
    build:
      context: Web
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  api:
    image: api
    depends_on:
      - reverseproxy 
    build:
      context: Api
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development #TODO: CHANGE THIS 
    ports:
      - 7167:7167