version: '3.4'

services:
  web:
    image: domshyra/containersdemo-web:local
    build:
      context: Web
      dockerfile: ./Dockerfile.debug
    environment:
      NODE_ENV: development
      API_URL: https://localhost:8001/
    ports:
      - 3000:3000
    volumes:
      - ./Web:/usr/src/app/ 
  api:
    image: domshyra/containersdemo-api:local
    build:
      context: Api
      dockerfile: ./Dockerfile.debug
    ports:
      - 8000:80
      - 8001:443
    restart: always
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+80
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${DEV_CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/api.pfx
      - USER_SECRETS_ID=836b9b8b-fd89-4aff-9286-809bda60998f
      - Spotify:ClientId=${SPOTIFY_CLIENT_ID}
      - Spotify:ClientSecret=${SPOTIFY_CLIENT_SECRET}
    volumes:
    # https://github.com/microsoft/DockerTools/issues/24#issuecomment-345450675
    # https://github.com/microsoft/DockerTools/issues/223#issuecomment-1148171934
    # https://github.com/dotnet/runtime/issues/36062#issuecomment-1107661688
      # - "${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets/:ro" # doesnt work
      - ~/.vsdbg:/remote_debugger:rw
      #- "${APPDATA}/microsoft/UserSecrets/:/root/.microsoft/usersecrets" #doesnt work
      - "${USERPROFILE}/.aspnet/https:/https/" #maps the https cert to the container
      #- "${APPDATA}/Microsoft/UserSecrets:/.microsoft/usersecrets/:ro" # doesnt work
      # - "${APPDATA}Microsoft/UserSecrets/836b9b8b-fd89-4aff-9286-809bda60998f:/root/.microsoft/usersecrets/836b9b8b-fd89-4aff-9286-809bda60998f" # doesnt work